### ISSUE TITLE
make run crash

### ISSUE THREAD

**Issue by v1xingyue** [danielsiwiec/fitnessTimer#1]
I have change properties.mk to my own . 
But when I run "make run " command . 
It crashed with message 。

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at com.garmin.monkeybrains.prgreader.EntryPoint.parse(EntryPoint.java:71)
	at com.garmin.monkeybrains.prgreader.EntryPoints.parse(EntryPoints.java:21)
	at com.garmin.monkeybrains.prgreader.PrgParser.parse(PrgParser.java:50)
	at com.garmin.monkeybrains.monkeydodeux.MonkeyDoDeux.execute(MonkeyDoDeux.java:244)
	at com.garmin.monkeybrains.monkeydodeux.MonkeyDoDeux.main(MonkeyDoDeux.java:146)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 5 more
make: *** [run] Error 1
```

seems something wrong , would you please help me ?

**Comment by tirkarthi** [comment]
I think it's caused to the usage of JDK 9 and above.

**Comment by danielsiwiec** [comment]
@qixingyue could you give it another try? I just updated the project to use most recent version of the seed project
